language: rust
rust:
  - 1.38.0  # minimal supported version
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  - cargo

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install --force cargo-audit
  - cargo generate-lockfile

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features --all -- -Dwarnings -W clippy::nursery -W clippy::pedantic
  - cargo test --all-features --all
  - cargo audit
